services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    working_dir: /workspace
    command: sh -c "pnpm install && pnpm -C apps/frontend dev"
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    volumes:
      - ./:/workspace
      - frontend_node_modules:/workspace/apps/frontend/node_modules
      - root_node_modules:/workspace/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=${API_BASE_URL:-http://localhost:8080}
      - REACT_APP_KEYCLOAK_URL=${KEYCLOAK_URL:-http://localhost:8080}

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    working_dir: /workspace
    command: sh -c "pnpm install && pnpm -C apps/backend dev"
    ports:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
    volumes:
      - ./:/workspace
      - backend_node_modules:/workspace/apps/backend/node_modules
      - root_node_modules:/workspace/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/procurement}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    depends_on:
      - mongodb
      - redis

  worker:
    build:
      context: ./apps/worker
      dockerfile: Dockerfile.dev
    working_dir: /workspace
    command: sh -c "pnpm install && pnpm -C apps/worker dev"
    volumes:
      - ./:/workspace
      - worker_node_modules:/workspace/apps/worker/node_modules
      - root_node_modules:/workspace/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/procurement}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev

volumes:
  mongodb_data:
  redis_data:
  frontend_node_modules:
  backend_node_modules:
  worker_node_modules:
  root_node_modules:

